"""Dynamics API: articles/notes generated by the intent reasoner."""

from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel
from sqlalchemy.orm import Session
from sqlalchemy import desc

from models import get_db, Dynamic
from services.scheduler import trigger_reasoning_now

router = APIRouter(prefix="/api/dynamics", tags=["dynamics"])


@router.get("")
def list_dynamics(
    page: int = Query(1, ge=1),
    page_size: int = Query(20, ge=1, le=100),
    category: str = None,
    device_id: str = None,
    db: Session = Depends(get_db),
):
    query = db.query(Dynamic).order_by(desc(Dynamic.is_pinned), desc(Dynamic.created_at))
    if category:
        query = query.filter(Dynamic.category == category)
    if device_id:
        query = query.filter(Dynamic.device_id == device_id)

    total = query.count()
    items = query.offset((page - 1) * page_size).limit(page_size).all()

    return {
        "total": total,
        "page": page,
        "page_size": page_size,
        "items": [
            {
                "id": d.id, "title": d.title, "summary": d.summary,
                "content": d.content, "category": d.category,
                "confidence": d.confidence, "is_read": d.is_read,
                "is_pinned": d.is_pinned, "device_id": d.device_id,
                "created_at": d.created_at.isoformat() if d.created_at else None,
            }
            for d in items
        ],
    }


@router.get("/unread-count")
def get_unread_count(device_id: str = None, db: Session = Depends(get_db)):
    query = db.query(Dynamic).filter(Dynamic.is_read == False)
    if device_id:
        query = query.filter(Dynamic.device_id == device_id)
    count = query.count()
    return {"unread_count": count}


@router.put("/read-all")
def mark_all_read(device_id: str = None, db: Session = Depends(get_db)):
    query = db.query(Dynamic).filter(Dynamic.is_read == False)
    if device_id:
        query = query.filter(Dynamic.device_id == device_id)
    updated = query.update({Dynamic.is_read: True})
    db.commit()
    return {"message": f"Marked {updated} dynamics as read"}


@router.get("/{dynamic_id}")
def get_dynamic(dynamic_id: int, db: Session = Depends(get_db)):
    d = db.query(Dynamic).filter(Dynamic.id == dynamic_id).first()
    if not d:
        raise HTTPException(status_code=404, detail="Dynamic not found")
    return {
        "id": d.id, "title": d.title, "summary": d.summary,
        "content": d.content, "category": d.category,
        "source_photo_ids": d.source_photo_ids,
        "source_conversation_ids": d.source_conversation_ids,
        "confidence": d.confidence, "is_read": d.is_read,
        "is_pinned": d.is_pinned, "device_id": d.device_id,
        "created_at": d.created_at.isoformat() if d.created_at else None,
    }


@router.put("/{dynamic_id}/read")
def mark_read(dynamic_id: int, db: Session = Depends(get_db)):
    d = db.query(Dynamic).filter(Dynamic.id == dynamic_id).first()
    if not d:
        raise HTTPException(status_code=404, detail="Dynamic not found")
    d.is_read = True
    db.commit()
    return {"message": "Marked as read"}


@router.put("/{dynamic_id}/pin")
def toggle_pin(dynamic_id: int, db: Session = Depends(get_db)):
    d = db.query(Dynamic).filter(Dynamic.id == dynamic_id).first()
    if not d:
        raise HTTPException(status_code=404, detail="Dynamic not found")
    d.is_pinned = not d.is_pinned
    db.commit()
    return {"is_pinned": d.is_pinned}


@router.delete("/{dynamic_id}")
def delete_dynamic(dynamic_id: int, db: Session = Depends(get_db)):
    d = db.query(Dynamic).filter(Dynamic.id == dynamic_id).first()
    if not d:
        raise HTTPException(status_code=404, detail="Dynamic not found")
    db.delete(d)
    db.commit()
    return {"message": "Deleted"}


@router.post("/trigger")
async def trigger_reasoning(device_id: str = None):
    """Manually trigger a reasoning cycle."""
    try:
        results = await trigger_reasoning_now(device_id)
        return {"generated": len(results), "articles": results}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Reasoning failed: {str(e)}")
