"""Dynamics API: articles/notes generated by the intent reasoner.

Supports cursor-based pagination for efficient scrolling through large datasets.
"""

from datetime import datetime
from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel
from sqlalchemy.orm import Session
from sqlalchemy import desc, func

from models import get_db, Dynamic
from services.scheduler import trigger_reasoning_now

router = APIRouter(prefix="/api/dynamics", tags=["dynamics"])


def _dynamic_to_dict(d: Dynamic, include_content: bool = False) -> dict:
    """Convert Dynamic to dict. Only include content when explicitly requested."""
    result = {
        "id": d.id,
        "title": d.title,
        "summary": d.summary,
        "category": d.category,
        "confidence": d.confidence,
        "is_read": d.is_read,
        "is_pinned": d.is_pinned,
        "device_id": d.device_id,
        "created_at": d.created_at.isoformat() if d.created_at else None,
    }
    if include_content:
        result["content"] = d.content
        result["source_photo_ids"] = d.source_photo_ids
        result["source_conversation_ids"] = d.source_conversation_ids
    return result


@router.get("")
def list_dynamics(
    cursor: int = Query(default=0, description="ID of the last item from previous page (for cursor pagination)"),
    limit: int = Query(default=30, ge=1, le=100),
    category: str = None,
    device_id: str = None,
    db: Session = Depends(get_db),
):
    """List dynamics with cursor-based pagination.

    - First call: cursor=0, returns the newest items
    - Next calls: cursor=<last item id>, returns older items
    - Pinned items always appear first
    """
    # Build base query
    query = db.query(Dynamic)

    if category:
        query = query.filter(Dynamic.category == category)
    if device_id:
        query = query.filter(Dynamic.device_id == device_id)

    # Cursor pagination: get items older than the cursor
    if cursor > 0:
        cursor_item = db.query(Dynamic).filter(Dynamic.id == cursor).first()
        if cursor_item:
            if cursor_item.is_pinned:
                query = query.filter(
                    (Dynamic.is_pinned == True) | (Dynamic.created_at < cursor_item.created_at)
                )
            else:
                query = query.filter(
                    (Dynamic.is_pinned == True) |
                    ((Dynamic.is_pinned == False) & (Dynamic.created_at < cursor_item.created_at))
                )

    # Order: pinned first, then by created_at desc
    query = query.order_by(desc(Dynamic.is_pinned), desc(Dynamic.created_at))
    items = query.limit(limit + 1).all()  # fetch one extra to check if more exist

    has_more = len(items) > limit
    if has_more:
        items = items[:limit]

    return {
        "items": [_dynamic_to_dict(d, include_content=False) for d in items],
        "next_cursor": items[-1].id if items else None,
        "has_more": has_more,
    }


@router.get("/stats")
def dynamics_stats(device_id: str = None, db: Session = Depends(get_db)):
    """Get unread counts per category."""
    query = db.query(
        Dynamic.category,
        func.count(Dynamic.id)
    ).filter(Dynamic.is_read == False)

    if device_id:
        query = query.filter(Dynamic.device_id == device_id)

    counts = dict(query.group_by(Dynamic.category).all())
    total_unread = sum(counts.values())

    return {
        "total_unread": total_unread,
        "by_category": counts,
    }


@router.get("/{dynamic_id}")
def get_dynamic(dynamic_id: int, db: Session = Depends(get_db)):
    """Get full dynamic content including body text."""
    d = db.query(Dynamic).filter(Dynamic.id == dynamic_id).first()
    if not d:
        raise HTTPException(status_code=404, detail="Dynamic not found")
    return _dynamic_to_dict(d, include_content=True)


@router.put("/{dynamic_id}/read")
def mark_read(dynamic_id: int, db: Session = Depends(get_db)):
    d = db.query(Dynamic).filter(Dynamic.id == dynamic_id).first()
    if not d:
        raise HTTPException(status_code=404, detail="Dynamic not found")
    d.is_read = True
    db.commit()
    return {"message": "Marked as read"}


@router.put("/read-all")
def mark_all_read(device_id: str = None, db: Session = Depends(get_db)):
    query = db.query(Dynamic).filter(Dynamic.is_read == False)
    if device_id:
        query = query.filter(Dynamic.device_id == device_id)
    updated = query.update({Dynamic.is_read: True})
    db.commit()
    return {"message": f"Marked {updated} dynamics as read"}


@router.put("/{dynamic_id}/pin")
def toggle_pin(dynamic_id: int, db: Session = Depends(get_db)):
    d = db.query(Dynamic).filter(Dynamic.id == dynamic_id).first()
    if not d:
        raise HTTPException(status_code=404, detail="Dynamic not found")
    d.is_pinned = not d.is_pinned
    db.commit()
    return {"is_pinned": d.is_pinned}


@router.delete("/{dynamic_id}")
def delete_dynamic(dynamic_id: int, db: Session = Depends(get_db)):
    d = db.query(Dynamic).filter(Dynamic.id == dynamic_id).first()
    if not d:
        raise HTTPException(status_code=404, detail="Dynamic not found")
    db.delete(d)
    db.commit()
    return {"message": "Deleted"}


@router.post("/trigger")
async def trigger_reasoning(device_id: str = None):
    """Manually trigger a reasoning cycle."""
    try:
        results = await trigger_reasoning_now(device_id)
        return {"generated": len(results), "articles": results}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Reasoning failed: {str(e)}")
